[tool.poetry]
name = "terraform-plugin"
version = "0.1.0"
description = "A framework to develop Terraform Plugins (Providers and Provisioners) in Python"
authors = ["Jian Yuan Lee <jianyuan@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
