# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: terraform/protos/grpc_stdio.proto
# plugin: grpclib.plugin.main
import abc
import typing

import google.protobuf.empty_pb2
import grpclib.client
import grpclib.const

import terraform.protos.grpc_stdio_pb2

if typing.TYPE_CHECKING:
    import grpclib.server


class GRPCStdioBase(abc.ABC):
    @abc.abstractmethod
    async def StreamStdio(
        self,
        stream: "grpclib.server.Stream[google.protobuf.empty_pb2.Empty, terraform.protos.grpc_stdio_pb2.StdioData]",
    ) -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            "/plugin.GRPCStdio/StreamStdio": grpclib.const.Handler(
                self.StreamStdio,
                grpclib.const.Cardinality.UNARY_STREAM,
                google.protobuf.empty_pb2.Empty,
                terraform.protos.grpc_stdio_pb2.StdioData,
            ),
        }


class GRPCStdioStub:
    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.StreamStdio = grpclib.client.UnaryStreamMethod(
            channel,
            "/plugin.GRPCStdio/StreamStdio",
            google.protobuf.empty_pb2.Empty,
            terraform.protos.grpc_stdio_pb2.StdioData,
        )
