# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: terraform/protos/tfplugin5_1.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.client
import grpclib.const

import terraform.protos.tfplugin5_1_pb2

if typing.TYPE_CHECKING:
    import grpclib.server


class ProviderBase(abc.ABC):
    @abc.abstractmethod
    async def GetSchema(
        self,
        stream: "grpclib.server.Stream[terraform.protos.tfplugin5_1_pb2.GetProviderSchema.Request, terraform.protos.tfplugin5_1_pb2.GetProviderSchema.Response]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def PrepareProviderConfig(
        self,
        stream: "grpclib.server.Stream[terraform.protos.tfplugin5_1_pb2.PrepareProviderConfig.Request, terraform.protos.tfplugin5_1_pb2.PrepareProviderConfig.Response]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def ValidateResourceTypeConfig(
        self,
        stream: "grpclib.server.Stream[terraform.protos.tfplugin5_1_pb2.ValidateResourceTypeConfig.Request, terraform.protos.tfplugin5_1_pb2.ValidateResourceTypeConfig.Response]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def ValidateDataSourceConfig(
        self,
        stream: "grpclib.server.Stream[terraform.protos.tfplugin5_1_pb2.ValidateDataSourceConfig.Request, terraform.protos.tfplugin5_1_pb2.ValidateDataSourceConfig.Response]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def UpgradeResourceState(
        self,
        stream: "grpclib.server.Stream[terraform.protos.tfplugin5_1_pb2.UpgradeResourceState.Request, terraform.protos.tfplugin5_1_pb2.UpgradeResourceState.Response]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def Configure(
        self,
        stream: "grpclib.server.Stream[terraform.protos.tfplugin5_1_pb2.Configure.Request, terraform.protos.tfplugin5_1_pb2.Configure.Response]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def ReadResource(
        self,
        stream: "grpclib.server.Stream[terraform.protos.tfplugin5_1_pb2.ReadResource.Request, terraform.protos.tfplugin5_1_pb2.ReadResource.Response]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def PlanResourceChange(
        self,
        stream: "grpclib.server.Stream[terraform.protos.tfplugin5_1_pb2.PlanResourceChange.Request, terraform.protos.tfplugin5_1_pb2.PlanResourceChange.Response]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def ApplyResourceChange(
        self,
        stream: "grpclib.server.Stream[terraform.protos.tfplugin5_1_pb2.ApplyResourceChange.Request, terraform.protos.tfplugin5_1_pb2.ApplyResourceChange.Response]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def ImportResourceState(
        self,
        stream: "grpclib.server.Stream[terraform.protos.tfplugin5_1_pb2.ImportResourceState.Request, terraform.protos.tfplugin5_1_pb2.ImportResourceState.Response]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def ReadDataSource(
        self,
        stream: "grpclib.server.Stream[terraform.protos.tfplugin5_1_pb2.ReadDataSource.Request, terraform.protos.tfplugin5_1_pb2.ReadDataSource.Response]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def Stop(
        self,
        stream: "grpclib.server.Stream[terraform.protos.tfplugin5_1_pb2.Stop.Request, terraform.protos.tfplugin5_1_pb2.Stop.Response]",
    ) -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            "/tfplugin5.Provider/GetSchema": grpclib.const.Handler(
                self.GetSchema,
                grpclib.const.Cardinality.UNARY_UNARY,
                terraform.protos.tfplugin5_1_pb2.GetProviderSchema.Request,
                terraform.protos.tfplugin5_1_pb2.GetProviderSchema.Response,
            ),
            "/tfplugin5.Provider/PrepareProviderConfig": grpclib.const.Handler(
                self.PrepareProviderConfig,
                grpclib.const.Cardinality.UNARY_UNARY,
                terraform.protos.tfplugin5_1_pb2.PrepareProviderConfig.Request,
                terraform.protos.tfplugin5_1_pb2.PrepareProviderConfig.Response,
            ),
            "/tfplugin5.Provider/ValidateResourceTypeConfig": grpclib.const.Handler(
                self.ValidateResourceTypeConfig,
                grpclib.const.Cardinality.UNARY_UNARY,
                terraform.protos.tfplugin5_1_pb2.ValidateResourceTypeConfig.Request,
                terraform.protos.tfplugin5_1_pb2.ValidateResourceTypeConfig.Response,
            ),
            "/tfplugin5.Provider/ValidateDataSourceConfig": grpclib.const.Handler(
                self.ValidateDataSourceConfig,
                grpclib.const.Cardinality.UNARY_UNARY,
                terraform.protos.tfplugin5_1_pb2.ValidateDataSourceConfig.Request,
                terraform.protos.tfplugin5_1_pb2.ValidateDataSourceConfig.Response,
            ),
            "/tfplugin5.Provider/UpgradeResourceState": grpclib.const.Handler(
                self.UpgradeResourceState,
                grpclib.const.Cardinality.UNARY_UNARY,
                terraform.protos.tfplugin5_1_pb2.UpgradeResourceState.Request,
                terraform.protos.tfplugin5_1_pb2.UpgradeResourceState.Response,
            ),
            "/tfplugin5.Provider/Configure": grpclib.const.Handler(
                self.Configure,
                grpclib.const.Cardinality.UNARY_UNARY,
                terraform.protos.tfplugin5_1_pb2.Configure.Request,
                terraform.protos.tfplugin5_1_pb2.Configure.Response,
            ),
            "/tfplugin5.Provider/ReadResource": grpclib.const.Handler(
                self.ReadResource,
                grpclib.const.Cardinality.UNARY_UNARY,
                terraform.protos.tfplugin5_1_pb2.ReadResource.Request,
                terraform.protos.tfplugin5_1_pb2.ReadResource.Response,
            ),
            "/tfplugin5.Provider/PlanResourceChange": grpclib.const.Handler(
                self.PlanResourceChange,
                grpclib.const.Cardinality.UNARY_UNARY,
                terraform.protos.tfplugin5_1_pb2.PlanResourceChange.Request,
                terraform.protos.tfplugin5_1_pb2.PlanResourceChange.Response,
            ),
            "/tfplugin5.Provider/ApplyResourceChange": grpclib.const.Handler(
                self.ApplyResourceChange,
                grpclib.const.Cardinality.UNARY_UNARY,
                terraform.protos.tfplugin5_1_pb2.ApplyResourceChange.Request,
                terraform.protos.tfplugin5_1_pb2.ApplyResourceChange.Response,
            ),
            "/tfplugin5.Provider/ImportResourceState": grpclib.const.Handler(
                self.ImportResourceState,
                grpclib.const.Cardinality.UNARY_UNARY,
                terraform.protos.tfplugin5_1_pb2.ImportResourceState.Request,
                terraform.protos.tfplugin5_1_pb2.ImportResourceState.Response,
            ),
            "/tfplugin5.Provider/ReadDataSource": grpclib.const.Handler(
                self.ReadDataSource,
                grpclib.const.Cardinality.UNARY_UNARY,
                terraform.protos.tfplugin5_1_pb2.ReadDataSource.Request,
                terraform.protos.tfplugin5_1_pb2.ReadDataSource.Response,
            ),
            "/tfplugin5.Provider/Stop": grpclib.const.Handler(
                self.Stop,
                grpclib.const.Cardinality.UNARY_UNARY,
                terraform.protos.tfplugin5_1_pb2.Stop.Request,
                terraform.protos.tfplugin5_1_pb2.Stop.Response,
            ),
        }


class ProviderStub:
    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.GetSchema = grpclib.client.UnaryUnaryMethod(
            channel,
            "/tfplugin5.Provider/GetSchema",
            terraform.protos.tfplugin5_1_pb2.GetProviderSchema.Request,
            terraform.protos.tfplugin5_1_pb2.GetProviderSchema.Response,
        )
        self.PrepareProviderConfig = grpclib.client.UnaryUnaryMethod(
            channel,
            "/tfplugin5.Provider/PrepareProviderConfig",
            terraform.protos.tfplugin5_1_pb2.PrepareProviderConfig.Request,
            terraform.protos.tfplugin5_1_pb2.PrepareProviderConfig.Response,
        )
        self.ValidateResourceTypeConfig = grpclib.client.UnaryUnaryMethod(
            channel,
            "/tfplugin5.Provider/ValidateResourceTypeConfig",
            terraform.protos.tfplugin5_1_pb2.ValidateResourceTypeConfig.Request,
            terraform.protos.tfplugin5_1_pb2.ValidateResourceTypeConfig.Response,
        )
        self.ValidateDataSourceConfig = grpclib.client.UnaryUnaryMethod(
            channel,
            "/tfplugin5.Provider/ValidateDataSourceConfig",
            terraform.protos.tfplugin5_1_pb2.ValidateDataSourceConfig.Request,
            terraform.protos.tfplugin5_1_pb2.ValidateDataSourceConfig.Response,
        )
        self.UpgradeResourceState = grpclib.client.UnaryUnaryMethod(
            channel,
            "/tfplugin5.Provider/UpgradeResourceState",
            terraform.protos.tfplugin5_1_pb2.UpgradeResourceState.Request,
            terraform.protos.tfplugin5_1_pb2.UpgradeResourceState.Response,
        )
        self.Configure = grpclib.client.UnaryUnaryMethod(
            channel,
            "/tfplugin5.Provider/Configure",
            terraform.protos.tfplugin5_1_pb2.Configure.Request,
            terraform.protos.tfplugin5_1_pb2.Configure.Response,
        )
        self.ReadResource = grpclib.client.UnaryUnaryMethod(
            channel,
            "/tfplugin5.Provider/ReadResource",
            terraform.protos.tfplugin5_1_pb2.ReadResource.Request,
            terraform.protos.tfplugin5_1_pb2.ReadResource.Response,
        )
        self.PlanResourceChange = grpclib.client.UnaryUnaryMethod(
            channel,
            "/tfplugin5.Provider/PlanResourceChange",
            terraform.protos.tfplugin5_1_pb2.PlanResourceChange.Request,
            terraform.protos.tfplugin5_1_pb2.PlanResourceChange.Response,
        )
        self.ApplyResourceChange = grpclib.client.UnaryUnaryMethod(
            channel,
            "/tfplugin5.Provider/ApplyResourceChange",
            terraform.protos.tfplugin5_1_pb2.ApplyResourceChange.Request,
            terraform.protos.tfplugin5_1_pb2.ApplyResourceChange.Response,
        )
        self.ImportResourceState = grpclib.client.UnaryUnaryMethod(
            channel,
            "/tfplugin5.Provider/ImportResourceState",
            terraform.protos.tfplugin5_1_pb2.ImportResourceState.Request,
            terraform.protos.tfplugin5_1_pb2.ImportResourceState.Response,
        )
        self.ReadDataSource = grpclib.client.UnaryUnaryMethod(
            channel,
            "/tfplugin5.Provider/ReadDataSource",
            terraform.protos.tfplugin5_1_pb2.ReadDataSource.Request,
            terraform.protos.tfplugin5_1_pb2.ReadDataSource.Response,
        )
        self.Stop = grpclib.client.UnaryUnaryMethod(
            channel,
            "/tfplugin5.Provider/Stop",
            terraform.protos.tfplugin5_1_pb2.Stop.Request,
            terraform.protos.tfplugin5_1_pb2.Stop.Response,
        )


class ProvisionerBase(abc.ABC):
    @abc.abstractmethod
    async def GetSchema(
        self,
        stream: "grpclib.server.Stream[terraform.protos.tfplugin5_1_pb2.GetProvisionerSchema.Request, terraform.protos.tfplugin5_1_pb2.GetProvisionerSchema.Response]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def ValidateProvisionerConfig(
        self,
        stream: "grpclib.server.Stream[terraform.protos.tfplugin5_1_pb2.ValidateProvisionerConfig.Request, terraform.protos.tfplugin5_1_pb2.ValidateProvisionerConfig.Response]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def ProvisionResource(
        self,
        stream: "grpclib.server.Stream[terraform.protos.tfplugin5_1_pb2.ProvisionResource.Request, terraform.protos.tfplugin5_1_pb2.ProvisionResource.Response]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def Stop(
        self,
        stream: "grpclib.server.Stream[terraform.protos.tfplugin5_1_pb2.Stop.Request, terraform.protos.tfplugin5_1_pb2.Stop.Response]",
    ) -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            "/tfplugin5.Provisioner/GetSchema": grpclib.const.Handler(
                self.GetSchema,
                grpclib.const.Cardinality.UNARY_UNARY,
                terraform.protos.tfplugin5_1_pb2.GetProvisionerSchema.Request,
                terraform.protos.tfplugin5_1_pb2.GetProvisionerSchema.Response,
            ),
            "/tfplugin5.Provisioner/ValidateProvisionerConfig": grpclib.const.Handler(
                self.ValidateProvisionerConfig,
                grpclib.const.Cardinality.UNARY_UNARY,
                terraform.protos.tfplugin5_1_pb2.ValidateProvisionerConfig.Request,
                terraform.protos.tfplugin5_1_pb2.ValidateProvisionerConfig.Response,
            ),
            "/tfplugin5.Provisioner/ProvisionResource": grpclib.const.Handler(
                self.ProvisionResource,
                grpclib.const.Cardinality.UNARY_STREAM,
                terraform.protos.tfplugin5_1_pb2.ProvisionResource.Request,
                terraform.protos.tfplugin5_1_pb2.ProvisionResource.Response,
            ),
            "/tfplugin5.Provisioner/Stop": grpclib.const.Handler(
                self.Stop,
                grpclib.const.Cardinality.UNARY_UNARY,
                terraform.protos.tfplugin5_1_pb2.Stop.Request,
                terraform.protos.tfplugin5_1_pb2.Stop.Response,
            ),
        }


class ProvisionerStub:
    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.GetSchema = grpclib.client.UnaryUnaryMethod(
            channel,
            "/tfplugin5.Provisioner/GetSchema",
            terraform.protos.tfplugin5_1_pb2.GetProvisionerSchema.Request,
            terraform.protos.tfplugin5_1_pb2.GetProvisionerSchema.Response,
        )
        self.ValidateProvisionerConfig = grpclib.client.UnaryUnaryMethod(
            channel,
            "/tfplugin5.Provisioner/ValidateProvisionerConfig",
            terraform.protos.tfplugin5_1_pb2.ValidateProvisionerConfig.Request,
            terraform.protos.tfplugin5_1_pb2.ValidateProvisionerConfig.Response,
        )
        self.ProvisionResource = grpclib.client.UnaryStreamMethod(
            channel,
            "/tfplugin5.Provisioner/ProvisionResource",
            terraform.protos.tfplugin5_1_pb2.ProvisionResource.Request,
            terraform.protos.tfplugin5_1_pb2.ProvisionResource.Response,
        )
        self.Stop = grpclib.client.UnaryUnaryMethod(
            channel,
            "/tfplugin5.Provisioner/Stop",
            terraform.protos.tfplugin5_1_pb2.Stop.Request,
            terraform.protos.tfplugin5_1_pb2.Stop.Response,
        )
